global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "web-metrics-api-ozornin"
    metrics_path: '/metrics'
    scrape_interval: 10s 
    static_configs:
      - targets: ["host.docker.internal:5009"]
