version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: RaspredeleniyeDutya
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "15432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql
    networks:
      - app-network

  app:
    build: .
    image: raspredeleniyedutyaapp
    container_name: aspnet_app
    ports:
      - "5009:5009"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=RaspredeleniyeDutya;Username=postgres;Password=admin
      - HostAppAddress=http://localhost:5009
    networks:
      - app-network

networks:
  app-network:
    driver: bridge